name: android_emulator
version: 0.0.1
language: android
description: Start an android emulator, which could run your tests in flow.ci
tags:
 - flow
 - plugin
 - emulator
 - android

public: true

inputs:
  - name: FLOW_ANDROID_SDK_VERSION
    editable: true
    desc_cn: "Android sdk 版本"
    desc_en: "Android sdk version"
    category: "select"
    options:
      - android-23=android-23
    default: 'android-23'

  - name: FLOW_ANDROID_CPU_VERSION
    editable: true
    desc_cn: "Android cpu 版本"
    desc_en: "Android cpu version"
    category: "select"
    options:
      - armeabi-v7a=armeabi-v7a
    default: 'armeabi-v7a'  

script_path: ./run.sh
